#!/usr/bin/env python3
"""Regenerate _System/file-map.md — a flat, complete enumeration of every
.md file in the vault, grouped by folder. Run from the vault root:

    python3 _System/gen-file-map.py

The file-map is a navigation aid for readers (incl. external chats) that
can't grep. It's a SNAPSHOT — regenerate after adding/moving/deleting files.
grep against the live tree is always authoritative if this looks stale.
"""
import os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SKIP_TOP = {".git", "_legacy", "_Private"}  # _Private = the gitignored Secret Document store — never enumerate it

groups = {}
for dp, dn, fn in os.walk(ROOT):
    dn[:] = [d for d in dn if not d.startswith(".") and d not in SKIP_TOP]
    mds = sorted(f for f in fn if f.endswith(".md"))
    if not mds:
        continue
    rel = os.path.relpath(dp, ROOT)
    if rel == ".":
        rel = "(root)"
    groups[rel] = mds

total = sum(len(v) for v in groups.values())

L = []
L += ["---", "type: reference", "citable: false", "status: stable", "---"]
L.append("# Vault File Map — complete enumeration")
L.append("")
L.append(f"**Every `.md` file in the vault, by folder ({total} files).** A flat, complete listing so any reader (incl. an external chat) can see *exactly what exists and where* without grep or guesswork. Companion to the curated [[index]] (which explains *what things mean*); this just lists *what's there*.")
L.append("")
L.append("> [!warning] Snapshot — may lag")
L.append("> Generated by `python3 _System/gen-file-map.py`; **regenerate after adding files.** If this looks stale, `grep -rli \"term\" .` against the live tree is authoritative. Registries with URLs/status: interviews+Mirror Sessions in [[Master Source List]] (§11/§2); IDs in [[Ontology]].")
L.append("")
L.append("**Regen:** `python3 _System/gen-file-map.py` — then commit. Last generated: see git.")
L.append("")

ORDER = [
    "(root)", "_System",
    "Sources/Lyrics", "Sources/Credits", "Sources/Quotes", "Sources/Transcripts",
    "Sources/Reference", "Sources/Artifacts",
    "Brain/Concepts", "Brain/Characters", "Brain/Albums", "Brain/Roy Voice",
    "Brain/Songs", "Brain/Songs/Subject to Flooding (2018)", "Brain/Songs/33 (2022)",
    "Brain/Songs/Lucius Lullaby (2026)", "Brain/Songs/Singles & EPs",
    "Essays/Concepts", "Essays/Concepts/Songs", "Essays/Characters", "Essays/Arcs",
]

seen = set()
def emit(g):
    if g in groups and g not in seen:
        seen.add(g)
        L.append(f"## {g}/  ({len(groups[g])})")
        for f in groups[g]:
            L.append(f"- {f}")
        L.append("")

for g in ORDER:
    emit(g)
for g in sorted(groups):
    emit(g)

with open(os.path.join(ROOT, "_System", "file-map.md"), "w") as fh:
    fh.write("\n".join(L) + "\n")

print(f"wrote _System/file-map.md · {total} files · {len(groups)} folders")
